# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Guest = User.create(username: "guest" password: "guest")
Kristen = User.create(username: "kristen" password: "kristen" )
AppAcademy = User.create(username: "appacademy" password: "appacademy" )
ParisHilton = User.create(username: "parishilton" password: "parishilton")
Obama = User.create(username: "obama" password: "obama")


Gizmo  = Pet.create( name: "Gizmo",    owner_id: Guest.id, animal: "cat", age: 1,  color: "black", gender: "M", bio: "Not yet potty trained", image_url: , address: "Pier 15" , city: "San Francisco" , state: "CA", zipcode:  )
Sandy  = Pet.create( name: "Sandy",    owner_id: Guest.id, animal: "cat", age: 5,  color: "gray",  gender: "F", bio: "Rescued from the streets", image_url: , address: "800 N Point St", city: "San Francisco" , state: "CA", zipcode: 94109  )
Jaguar = Pet.create( name: "Jaguar",   owner_id: Guest.id, animal: "cat", age: 5,  color: "white", gender: "M", bio: "Professionally trained", image_url: , address: "584 Washington Street", city: "San Francisco" , state: "CA", zipcode:  94111 )
Bella  = Pet.create( name: "Bella",    owner_id: Guest.id, animal: "cat", age: 10, color: "gray",  gender: "F", bio: "Likes to chase mice", image_url: , address: "178 Townsend St.", city: "San Francisco" , state: "CA", zipcode: 94107  )
Ginger = Pet.create( name: "Ginger",   owner_id: Kristen.id, animal: "cat", age: 7,  color: "yellow",gender: "M", bio: "Very jumpy, likes to climb on people", image_url: , address: "1700 Post St." , city: "San Francisco" , state: "CA", zipcode: 94115 )
Lily   = Pet.create( name: "Lily",     owner_id: Kristen.id, animal: "cat", age: 2,  color: "black", gender: "F", bio: "Likes to go on longs walks", image_url: , address: "2316 Polk St.", city: "San Francisco" , state: "CA" , zipcode: 94109   )
Oscar  = Pet.create( name: "Oscar",    owner_id: Kristen.id, animal: "cat", age: 8,  color: "brown",  gender: "M", bio: "Sleeps all day long" , image_url: , address: "1 Mission Street", city: "San Francisco" , state: "CA" , zipcode: 94105   )
Tiger  = Pet.create( name: "Tiger",    owner_id: AppAcademy.id, animal: "cat", age: 5,  color: "black", gender: "M", bio: "Behaves well if not hungry", image_url: , address: "1 Kearny St.", city: "San Francisco" , state: "CA" , zipcode: 94108   )
Coco   = Pet.create( name: "Coco",     owner_id: AppAcademy.id, animal: "cat", age: 7,  color: "white", gender: "F", bio: "Digs holes outside on the ground"  , image_url: , address: "3640 Sacramento St.", city: "San Francisco" , state: "CA" , zipcode: 94118 )
Simba  = Pet.create( name: "Simba",    owner_id: AppAcademy.id, animal: "cat", age: 5,  color: "brown", gender: "M", bio: "Very gentle with people, likes to be held", image_url: , address: "1722 Sacramento St." , city: "San Francisco" , state: "CA" , zipcode: 94109  )
Misty  = Pet.create( name: "Misty",    owner_id: ParisHilton.id, animal: "cat", age: 10, color: "gray",  gender: "F", bio: "Wery calm and well mannered", image_url: , address: "3859 Piedmont Ave", city: "San Francisco" , state: "CA" , zipcode: 94611   )
Smokey = Pet.create( name: "Smokey",   owner_id: ParisHilton.id, animal: "cat", age: 7,  color: "yellow",gender: "M", bio: "Will follow you if you leave the house", image_url: , address: "178 Townsend St.", city: "San Francisco" , state: "CA" , zipcode: 94107 )
Lucy   = Pet.create( name: "Lucy",     owner_id: ParisHilton.id, animal: "cat", age: 2,  color: "black", gender: "F", bio: "Does not like to be startled", image_url: , address: "16 Washington St", city: "San Francisco" , state: "CA" , zipcode: 94015   )
Max    = Pet.create( name: "Max",      owner_id: Obama.id, animal: "cat", age: 8,  color: "brown",  gender: "M", bio: "Likes to play with tennis balls" , image_url: , address: "7031 Mission St.", city: "San Francisco" , state: "CA" , zipcode: 94014   )
DrEvil = Pet.create( name: "Dr. Evil", owner_id: Obama.id, animal: "cat", age: 8,  color: "gray",  gender: "M", bio: "Likes to play with tennis balls" , image_url: , address: "101 S Mayfair Ave" , city: "San Francisco" , state: "CA" , zipcode:  94015  )


PetRentalRequest.create(pet_id: Gizmo.id,  requester_id: Kristen.id,     start_date: "08/05/2014".to_datetime, end_date:"08/08/2014".to_datetime)
PetRentalRequest.create(pet_id: Gizmo.id,  requester_id: AppAcademy.id,  start_date: "08/06/2014".to_datetime  end_date:"08/11/2014".to_datetime)
PetRentalRequest.create(pet_id: Sandy.id,  requester_id: ParisHilton.id, start_date: "08/02/2014".to_datetime  end_date:"08/12/2014".to_datetime)
PetRentalRequest.create(pet_id: Sandy.id,  requester_id: Obama.id,       start_date: "08/01/2014".to_datetime  end_date:"08/05/2014".to_datetime)
PetRentalRequest.create(pet_id: Jaguar.id, requester_id: Kristen.id,     start_date: "08/09/2014".to_datetime  end_date:"08/15/2014".to_datetime)
PetRentalRequest.create(pet_id: Jaguar.id, requester_id: AppAcademy.id,  start_date: "08/11/2014".to_datetime  end_date:"08/15/2014".to_datetime)
PetRentalRequest.create(pet_id: Bella.id,  requester_id: ParisHilton.id, start_date: "08/06/2014".to_datetime, end_date:"08/15/2014".to_datetime)
PetRentalRequest.create(pet_id: Bella.id,  requester_id: Obama.id,       start_date: "08/12/2014".to_datetime, end_date:"08/25/2014".to_datetime)
PetRentalRequest.create(pet_id: Bella.id,  requester_id: Kristen.id,     start_date: "08/21/2014".to_datetime, end_date:"08/27/2014".to_datetime)
PetRentalRequest.create(pet_id: Bella.id,  requester_id: AppAcademy.id,  start_date: "08/08/2014".to_datetime, end_date:"08/18/2014".to_datetime)
PetRentalRequest.create(pet_id: Bella.id,  requester_id: Obama.id,       start_date: "08/07/2014".to_datetime, end_date:"08/15/2014".to_datetime)
PetRentalRequest.create(pet_id: Ginger.id, requester_id: ParisHilton.id, start_date: "08/05/2014".to_datetime  end_date:"08/22/2014".to_datetime)
PetRentalRequest.create(pet_id: Lily.id,   requester_id: Guest.id,       start_date: "08/14/2014".to_datetime  end_date:"08/20/2014".to_datetime)
PetRentalRequest.create(pet_id: Oscar.id,  requester_id: Guest.id,       start_date: "08/12/2014".to_datetime  end_date:"08/28/2014".to_datetime)
PetRentalRequest.create(pet_id: Tiger.id,  requester_id: Obama.id,       start_date: "08/21/2014".to_datetime, end_date:"08/22/2014".to_datetime)
PetRentalRequest.create(pet_id: Coco.id,   requester_id: ParisHilton.id, start_date: "08/25/2014".to_datetime  end_date:"08/28/2014".to_datetime)
PetRentalRequest.create(pet_id: Simba.id,  requester_id: Kristen.id,     start_date: "08/14/2014".to_datetime  end_date:"08/25/2014".to_datetime)
PetRentalRequest.create(pet_id: Simba.id,  requester_id: Guest.id,       start_date: "08/17/2014".to_datetime  end_date:"08/30/2014".to_datetime)
PetRentalRequest.create(pet_id: Misty.id,  requester_id: Guest.id,       start_date: "08/21/2014".to_datetime  end_date:"09/21/2014".to_datetime)
PetRentalRequest.create(pet_id: Smokey.id, requester_id: Kristen.id,     start_date: "08/16/2014".to_datetime, end_date:"08/29/2014".to_datetime)
PetRentalRequest.create(pet_id: Lucy.id,   requester_id: Guest.id,       start_date: "08/04/2014".to_datetime  end_date:"08/07/2014".to_datetime)
PetRentalRequest.create(pet_id: DrEvil.id, requester_id: ParisHilton.id, start_date: "08/26/2014".to_datetime  end_date:"08/27/2014".to_datetime)



Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )
Image.create(pet_id: , image_url: )